quarkus:  
  banner:    
    # remove quarkus logo at startup logs
    enabled: false

  log:
    level: INFO

"%prod":
  vault:
    url: http://localhost:8200

    # vault authentication
    authentication:
      userpass:
        username: bob
        password: sinclair

    # path within the kv secret engine where is located the vault-quickstart secret configuration
    secret-config-kv-path: secret/myapp/config
  
"%dev":
  quarkus:
    vault:
      devservices:
        init-commands: 'kv put secret/config password="p@$$w0rd"'
        #port: 54995

    log:
      category:
        "com.microservice.quarkus":
          level: DEBUG
        "io.quarkus.vault":
          level: DEBUG
      file:
        enable: true
        path: target/quarkus.log
        level: ALL   